name: Ejecutar Análisis Birdeye
on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos
  workflow_dispatch:  # Ejecución manual

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependencias
        run: |
          npm install
          npm install -g esbuild
        
      - name: Run Birdeye
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          WORKER_URL: ${{ secrets.WORKER_URL }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MIN_SWAP_USD: 5000
        run: |
          node --experimental-vm-modules netlify/functions/birdeye.js
